2.2.9

diff --git a/functions/04_update b/functions/04_update
--- a/functions/04_update
+++ b/functions/04_update
@@ -9,68 +9,78 @@ function update
     fi
 
     # Fonction lançant les mises à jour yum
-    {
-        echo -e "\nUpdate is running..."
+    
+    echo -e "\nUpdate is running..."
 
-        echo -ne "Cleaning cache: "
+    echo -ne "Cleaning cache: "
+    if [ "$OS_FAMILY" == "Redhat" ];then
+        checkYumLock
+        yum clean all -q
+    fi
+    if [ "$OS_FAMILY" == "Debian" ];then
+        apt-get clean
+    fi
+
+    echo -e "[$GREEN OK $RESET]"
+
+    # Si c'est du Debian, on charge la liste des paquets
+    if [ "$OS_FAMILY" == "Debian" ];then
+        apt-get -o Acquire::Check-Valid-Until=false -qq --allow-releaseinfo-change update
+    fi
+
+    # Si $UPDATE_EXCLUDE n'est pas vide, alors on exclu les paquets de la mise à jour
+    if [ ! -z "$UPDATE_EXCLUDE" ];then
         if [ "$OS_FAMILY" == "Redhat" ];then
-            checkYumLock
-            yum clean all -q
+            YUM_OPTIONS+=" --exclude=${UPDATE_EXCLUDE}"
+            # Trim whitespaces
+            YUM_OPTIONS="${YUM_OPTIONS#"${YUM_OPTIONS%%[![:space:]]*}"}"
+            YUM_OPTIONS="${YUM_OPTIONS%"${YUM_OPTIONS##*[![:space:]]}"}"
         fi
+
         if [ "$OS_FAMILY" == "Debian" ];then
-            apt-get clean
+            echo -e "\nExcluding critical packages: $YELLOW"
+            IFS=' '
+
+            for PACKAGE in ${UPDATE_EXCLUDE[@]};do # Attention ne pas placer de double quote sur cette variable
+                apt-mark hold "$PACKAGE"
+                if [ "$?" -eq "0" ];then
+                    echo -e "Error while excluding $PACKAGE"
+                    (( UPDATE_ERROR++ ))
+                    return
+                fi
+            done
+
+            echo -e "$RESET"
         fi
+    fi
 
-        echo -e "[$GREEN OK $RESET]"
-
-        # echo -e "\nInstallation des mises à jour :"
-
-        # Si c'est du Debian, on charge la liste des paquets
-        if [ "$OS_FAMILY" == "Debian" ];then
-            apt-get -o Acquire::Check-Valid-Until=false -qq --allow-releaseinfo-change update
+    # Updating packages
+    if [ "$OS_FAMILY" == "Redhat" ];then
+        if [ ! -z "$YUM_OPTIONS" ];then
+            yum "$YUM_OPTIONS" update -y
+        else
+            yum update -y
         fi
-
-        # Si $UPDATE_EXCLUDE n'est pas vide, alors on exclu les paquets de la mise à jour
-        if [ ! -z "$UPDATE_EXCLUDE" ];then
-            if [ "$OS_FAMILY" == "Redhat" ];then
-                YUM_OPTIONS+=" --exclude=${UPDATE_EXCLUDE}"
-                # Trim whitespaces
-                YUM_OPTIONS="${YUM_OPTIONS#"${YUM_OPTIONS%%[![:space:]]*}"}"
-                YUM_OPTIONS="${YUM_OPTIONS%"${YUM_OPTIONS##*[![:space:]]}"}"
-            fi
-            if [ "$OS_FAMILY" == "Debian" ];then
-                echo -e "\nExcluding critical packages: $YELLOW"
-
-                IFS=' '
-                for PACKAGE in ${UPDATE_EXCLUDE[@]};do # Attention ne pas placer de double quote sur cette variable
-                    apt-mark hold "$PACKAGE"
-                done
-
-                echo -e "$RESET"
-            fi
+        if [ "$?" -ne "0" ];then
+            (( UPDATE_ERROR++ ))
         fi
+    fi
 
-        # Updating packages
-        if [ "$OS_FAMILY" == "Redhat" ];then
-            if [ ! -z "$YUM_OPTIONS" ];then
-                yum "$YUM_OPTIONS" update -y
-            else
-                yum update -y
-            fi
+    if [ "$OS_FAMILY" == "Debian" ];then
+        if [ ! -z "$APT_OPTIONS" ];then
+            apt-get "$APT_UPGRADE" -y "$APT_OPTIONS"
+        else
+            apt-get "$APT_UPGRADE" -y
         fi
-        if [ "$OS_FAMILY" == "Debian" ];then
-            if [ ! -z "$APT_OPTIONS" ];then
-                apt-get "$APT_UPGRADE" -y "$APT_OPTIONS"
-            else
-                apt-get "$APT_UPGRADE" -y
-            fi
+        if [ "$?" -ne "0" ];then
+            (( UPDATE_ERROR++ ))
         fi
+    fi
 
-        echo -e "\n${GREEN}Update completed${RESET}\n"
+    if [ "$UPDATE_ERROR" -gt "0" ];then
+        echo -e "\n${RED}Update has failed${RESET}"
+        return
+    fi
 
-    # If one command fail    
-    } || {
-        echo -e "\n${YELLOW}Update has failed${RESET}"
-        (( UPDATE_ERROR++ ))
-    }
+    echo -e "\n${GREEN}Update completed${RESET}\n"
 }
